### ISSUE TITLE
Log file not updating

### ISSUE THREAD

**Issue by lyrwang** [mattheww95/CrispyCody#3]
Hi Matthew,

It looks like the log output is not updating the name of the bam file being used for each sample. Example output is below.

"Sample being used 20-ARNI-WW-4.trim.mkD.sorted and 21-ARNI-WW7-VNL_combined.bam
Breadth of coverage for 20-ARNI-WW-4.trim.mkD.sorted is 4.04 %, with a genome length of 29903.A total of 765 N's were found with 27931 missing positions."

Thanks!
Ruth

**Comment by mattheww95** [comment]
Thank you for your patience the issue has been resolved!
